# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='search_term',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='television',
            name='top_3',
            field=models.BooleanField(default=False),
        ),
    ]
