# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-08 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceweb', '0003_auto_20170908_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='search_date',
            field=models.DateField(default=datetime.date(2017, 9, 8)),
        ),
    ]
