# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-15 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('priceweb', '0004_auto_20170908_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='search_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
